### ISSUE TITLE
XmlDiffPatch.View.dll: 'No matching node:4197'

### ISSUE THREAD

**Issue by RudyCo** [lovettchris/xmldiff#4]
Hello,
I am comparing several XML files and for one of them, I got the following exception.
The 2 XML files are valid XML files.
Thanks in advance.

```
An unhandled exception of type 'System.Exception' occurred in XmlDiffPatch.View.dll: 'No matching node:4197'
   at Microsoft.XmlDiffPatch.XmlDiffPath.OnNoMatchingNode(String path)
   at Microsoft.XmlDiffPatch.XmlDiffPath.SelectChildNodes(XmlDiffViewParentNode parentNode, String path, Int32 startPos)
   at Microsoft.XmlDiffPatch.XmlDiffPath.SelectNodes(XmlDiffViewParentNode rootNode, XmlDiffViewParentNode currentParentNode, String xmlDiffPathExpr)
   at Microsoft.XmlDiffPatch.XmlDiffView.ApplyDiffgram(XmlNode diffgramParent, XmlDiffViewParentNode sourceParent)
   at Microsoft.XmlDiffPatch.XmlDiffView.OnRemove(XmlElement diffgramElement, XmlDiffPathNodeList matchNodes, XmlDiffViewParentNode sourceParent, XmlDiffViewNode& currentPosition)
   at Microsoft.XmlDiffPatch.XmlDiffView.ApplyDiffgram(XmlNode diffgramParent, XmlDiffViewParentNode sourceParent)
   at Microsoft.XmlDiffPatch.XmlDiffView.ApplyDiffgram(XmlNode diffgramParent, XmlDiffViewParentNode sourceParent)
   at Microsoft.XmlDiffPatch.XmlDiffView.Load(XmlTextReader sourceXml, XmlReader diffGram)
   at Microsoft.XmlDiffPatch.XmlDiffView.MergeDiffgramAndBaseline(String sourceXmlFile, Boolean fragment)
   at Microsoft.XmlDiffPatch.XmlDiffView.MarkupBaselineWithChanges(String sourceXmlFile, String changedXmlFile, Boolean fragment, XmlDiffOptions options)
   at Microsoft.XmlDiffPatch.XmlDiffView.InternalDifferencesSideBySideAsHtml(String sourceXmlFile, String changedXmlFile, Boolean fragment, XmlDiffOptions options, Boolean omitIdenticalHtmlOutput, TextWriter resultHtml)
   at Microsoft.XmlDiffPatch.XmlDiffView.DifferencesSideBySideAsHtml(String sourceXmlFile, String changedXmlFile, Boolean fragment, XmlDiffOptions options, Boolean omitIdenticalHtmlOutput)
```

**Comment by lovettchris** [comment]
Looks like you found a bug, can you attach the 2 xml files so I can debug this?  If you don't want to make them public, can you email them to me using the email address you see in my profile?
